### ISSUE TITLE
404 for /static/css/blog.css on Heroku

### ISSUE THREAD

**Issue by alexgiann** [DjangoGirls/tutorial#329]
I added whitenoise from the updated french tutorial, but even with Debug= True heroku did not serve the static files at all. I used a suggestion from the django tutorial (https://docs.djangoproject.com/en/1.8/ref/contrib/staticfiles/#django.contrib.staticfiles.urls.staticfiles_urlpatterns) to insert in my url.py: 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

which only works when the Debug = True, and it did! But this is not a suggested permanent solution.  

I also tried the heroku suggestions to create the collectstatic dir but again, it didn't serve the static files with Debug=False. Here's the repo if you have any suggestions about how to fix this: https://github.com/alexgiann/geekeuse
Thanks!

**Comment by nnkps** [comment]
I think that the problem is that you didn't run the command
django-admin startproject mysite .
but
django-admin startproject mysite
and your application content is placed now in mysite/ where it should be in / directory
Try changing your project structure to the one shown in tutorial or removing mysite directory from home directory and running command again. I think this should solve the problem. Let me know if it's working.

**Comment by alexgiann** [comment]
Hi, 

I managed to change the dirs back as they should be according to the tutorial, but unfortunately it still doesn't work. I'm adding the extra commands back and leave this problem for the end of the tutorial.
